baseURL = "http://example.org/"
languageCode = "en-us"
title = "Il Segna vento"
theme = "elate"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Gioele Bonifetto"
  description = "developer"
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Elate"
    home = "Home"
    work = "In evidenza"
    about = "Chi siamo"
    contact = "Contattaci"

  # Hero section
  [params.hero]
    title = "Il Segna vento"
    subtitle = ''
 
  # Work section
  [params.work]
    enable = true
    title = "In evidenza"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # About section
  [params.about]
    enable = true
    title = "Chi siamo"
    description = "La famiglia Bonifetto si diletta nell'arte del commercio da quasi un secolo."

    [[params.about.item]]
      name = "Emiliano Bonifetto"
      position = "Agente di commercio"
      description = "È in attività da circa 45 anni. Con le sue collaborazioni ha dato vita a una vera e propria rete di negozi su tutto il paese. Riuscirebbe a venderti le mutande che indossi in questo momento."
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Paola Bonifetto"
      position = "Agente di commercio"
      description = "Nominata quest'anno come migliore agente KN industries, Paola affianca Emiliano da qualche anno garantendo ai suoi clienti assistenza, freschezza e un gran sorriso."
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]     

# Counters section
  [params.counters]
    enable = true
    title = "Qualche numero"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Regioni"
      icon = "icon-puzzle"
      from = 0
      to = 6
      interval = 30
      speed = 5000

    [[params.counters.item]]
      description = "Città"
      icon = "icon-location-pin"
      from = 0
      to = 57
      interval = 30
      speed = 5000

    [[params.counters.item]]
      description = "Clienti"
      icon = "icon-people"
      from = 0
      to = 73
      interval = 30
      speed = 5000

    [[params.counters.item]]
      description = "Ordini"
      icon = "icon-call-in"
      from = 0
      to = 248
      interval = 30
      speed = 5000


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contattaci"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]